#!/bin/bash

exec 2>&1
exec /usr/local/bin/flanneld  \
	--etcd-endpoints={% for host in groups['masters'] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %} \
	--ip-masq=true \
	--v=3 \

