# Usage:
#  ansible-playbook -i ./hosts ./bench.yml -vv
#

- hosts: bench
  sudo: yes

  vars_files:
  - vars.yml

  vars:
    kube_daemons: [ ]
    other_daemons: [ 'flanneld', 'irq_set' ]
    packages: 
      - apt-transport-https
      - ca-certificates
      - bridge-utils
      - sudo
      - aptitude
      - libpam-systemd
      - tcpdump
      - psmisc
      - dstat
      - ethtool

  tasks:

  - template: src=files/node/etc/apt/apt.conf dest=/etc/apt/apt.conf
  - apt: update_cache=yes

  - apt: pkg={{ item }} state=present
    with_items:
      - "{{ packages }}"

  - apt: upgrade=yes

########## PKI

  - local_action: file path={{ pki_dir }} state=directory

  - local_action: template src=files/pki/openssl.cnf dest={{ pki_dir }}/{{ ansible_default_ipv4.address }}.cnf
  - local_action: shell openssl genrsa -out {{ pki_dir }}/{{ ansible_default_ipv4.address }}.key 2048
  - local_action: shell openssl req -new -key {{ pki_dir }}/{{ ansible_default_ipv4.address }}.key -subj "/CN={{ ansible_default_ipv4.address }}" -out {{ pki_dir }}/{{ ansible_default_ipv4.address }}.csr -config {{ pki_dir }}/{{ ansible_default_ipv4.address }}.cnf
  - local_action: shell while ! (mkdir {{ lock_dir }} && openssl x509 -req -in {{ pki_dir }}/{{ ansible_default_ipv4.address }}.csr -CA {{ pki_dir }}/ca.crt -CAkey {{ pki_dir }}/ca.key -CAcreateserial -out {{ pki_dir }}/{{ ansible_default_ipv4.address }}.crt -days 10000  -extensions v3_req -extfile {{ pki_dir }}/{{ ansible_default_ipv4.address }}.cnf && rm -r {{ lock_dir }}) ; do sleep 1 ; done

  - file: path=/var/lib/kubelet/tls state=directory
  - template: src=./files/node/var/lib/kubelet/kubeconfig dest=/var/lib/kubelet/kubeconfig
  - copy: src={{ pki_dir }}/ca.crt dest=/var/lib/kubelet/tls/ca.crt mode=0700
  - copy: src={{ pki_dir }}/{{ ansible_default_ipv4.address }}.key dest=/var/lib/kubelet/tls/kubelet.key mode=0700
  - copy: src={{ pki_dir }}/{{ ansible_default_ipv4.address }}.crt dest=/var/lib/kubelet/tls/kubelet.crt mode=0700


  - unarchive: src=./files/common/usr/local/bin/{{ item }} dest=/usr/local/bin/
    with_items:
      - hyperkube.tar.xz
      - etcdctl.tar.xz
      - flanneld.tar.xz
    notify: daemon-restart

  - file: src=hyperkube dest=/usr/local/bin/{{ item }} state=link
    with_items:
      - kubectl

  - file: src=hyperkube dest=/usr/local/bin/{{ item }} state=link
    with_items:
      - "{{ kube_daemons }}"
    notify: daemon-restart

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:
      - "{{ kube_daemons }}"
      - "{{ other_daemons }}"

  - template: src=./files/node/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run mode=0700
    with_items:
      - "{{ kube_daemons }}"
      - "{{ other_daemons }}"
    notify: daemon-restart

  - template: src=./files/node/usr/service/{{ item }}/log/run dest=/usr/service/{{ item }}/log/run mode=0700
    with_items:
      - "{{ kube_daemons }}"
      - "{{ other_daemons }}"
    notify: daemon-restart

  - file: path=/etc/service/ state=directory mode=0755

  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - "{{ kube_daemons }}"
      - "{{ other_daemons }}"
    notify: daemon-restart

  - apt: pkg={{ item }} state=present
    with_items:
      - daemontools-run
    notify: daemon-restart

  - copy: src=./files/test/wrk dest=/usr/bin/wrk mode=0755

  - sysctl: name=net.ipv4.tcp_tw_reuse value="1" sysctl_set=yes
  - sysctl: name=net.core.somaxconn value="8192" sysctl_set=yes
  - sysctl: name=net.core.netdev_max_backlog value="65536" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_slow_start_after_idle value="0" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_autocorking value="0" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_syncookies value="0" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_max_syn_backlog value="65536" sysctl_set=yes
  - sysctl: name=net.core.rmem_max value="8388608" sysctl_set=yes
  - sysctl: name=net.core.wmem_max value="8388608" sysctl_set=yes
  - sysctl: name=net.core.rmem_default value="8388608" sysctl_set=yes
  - sysctl: name=net.core.wmem_default value="8388608" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_mem value="4096   8388608   8388608" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_rmem value="4096   8388608   8388608" sysctl_set=yes
  - sysctl: name=net.ipv4.tcp_wmem value="4096   8388608   8388608" sysctl_set=yes reload=yes

  - sysctl: name=net.netfilter.nf_conntrack_max value=20000000 sysctl_set=yes
  - sysctl: name=net.nf_conntrack_max value=20000000 sysctl_set=yes

  - sysctl: name=net.ipv4.tcp_syn_retries value="3" sysctl_set=yes

  handlers:

  - name: daemon-restart
    shell: 'svc -t /etc/service/* ; sleep 3'

