# Usage:
#  ansible-playbook -i ./hosts ./lvs.yml -vv
#

- hosts: lvs
  sudo: yes

  vars_files:
  - vars.yml

  vars:
    other_daemons: [ ]

  tasks:

##### keepalived

  - apt: pkg={{ item }} state=present
    with_items:
      - netcat

  - local_action: shell kubectl label node {{ inventory_hostname }} role=lvs --overwrite

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:
      - "{{ other_daemons }}"

  - template: src=./files/lvs/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run mode=0700
    with_items:
      - "{{ other_daemons }}"
    notify: daemon-restart

  - template: src=./files/lvs/usr/service/{{ item }}/log/run dest=/usr/service/{{ item }}/log/run mode=0700
    with_items:
      - "{{ other_daemons }}"
    notify: daemon-restart

  - file: path=/etc/service/ state=directory mode=0755

  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - "{{ other_daemons }}"
    notify: daemon-restart

### This is required for keepalived in default net_ns
  - sysctl:
      name: net.ipv4.igmp_max_memberships
      value: 20

  - sysctl:
      name: net.ipv4.conf.eth0.proxy_arp
      value: 1

  handlers:

  - name: daemon-restart
    shell: 'svc -t /etc/service/{{ item }}'
    with_items:
      - "{{ other_daemons }}"

