# Usage:
#  ansible-playbook -i ./hosts ./lvs.yml -vv
#

- hosts: lvs
  sudo: yes

  vars_files:
  - vars.yml

  tasks:

##### keepalived

  - apt: pkg={{ item }} state=present
    with_items:
      - netcat

  - local_action: shell kubectl label node {{ ansible_hostname }} role=lvs --overwrite

  - template: src=./files/node/etc/network/if-up.d/route dest=/etc/network/if-up.d/route mode=0755
    notify: add route

  handlers:

  - name: add route
    shell: /etc/network/if-up.d/route

