# Usage:
#  ansible-playbook -i ./hosts ./lvs.yml -vv
#

- hosts: lvs
  remote_user: root

  tasks:

##### keepalived

  - apt: pkg={{ item }} state=present
    with_items:
      - netcat

  - local_action: shell kubectl label node {{ ansible_hostname }} role=lvs --overwrite

