- hosts: masters 
  become: yes
  become_user: root

  vars_files:
  - vars.yml

  tasks:

  vars:
    daemons: [ 'etcd', 'apiserver', 'controller-manager', 'scheduler' ]
#    daemons: [ 'etcd' ]
    packages:
      - apt-transport-https
      - ca-certificates
      - bridge-utils
      - sudo
      - aptitude
      - libpam-systemd
      - tinyproxy
      - apt-cacher-ng
      - unzip

  tasks:

  - apt: update_cache=yes

  - apt: pkg={{ item }} state=present
    with_items:
      - "{{ packages }}"

  - apt: upgrade=yes

  - name: Download kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/{{ item }}
      dest: files/common/usr/local/bin/{{ item }}
      mode: 0755
      force: yes
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - kubectl
    run_once: true
    delegate_to: 127.0.0.1

  - name: Download etcd
    local_action: shell wget -q https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz -O - \
      |tar zxvf - -C files/common/usr/local/bin/ etcd-{{ etcd_version }}-linux-amd64/etcd etcd-{{ etcd_version }}-linux-amd64/etcdctl  --strip=1 
    run_once: true

  - name: Copy binaries 
    copy: src=files/common/usr/local/bin/{{ item }} dest=/usr/local/bin/{{ item }} mode=0755
    with_items: 
      - etcd
      - etcdctl
      - kubectl
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

  - name: Etcd directory
    file: path={{ item }} state=directory
    with_items:
      - /etc/etcd
      - /var/lib/etcd

  - name: Copy the certificates and private keys to masters
    copy: src={{ pki_dir }}/{{ item }} dest=/etc/etcd
    with_items: 
      - ca.pem
      - kubernetes.pem
      - kubernetes-key.pem

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - template: src=./files/master/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run mode=0700
    with_items:
      - "{{ daemons }}"

  - template: src=./files/master/usr/service/{{ item }}/log/run dest=/usr/service/{{ item }}/log/run mode=0700
    with_items:
      - "{{ daemons }}"

  - file: path=/etc/service/ state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - "{{ daemons }}"

  - apt: pkg={{ item }} state=present
    with_items:
      - daemontools-run

  - shell: 'svc -t /etc/service/* ; sleep 5'

  - copy: src=files/master/rbac.yml  dest=./rbac.yml 
    run_once: true

  - shell: kubectl apply -f ./rbac.yml
    run_once: true


