# Usage:
#  ansible-playbook -i ./hosts ./registry.yml -vv
#

- hosts: masters
  sudo: yes
  sudo_user: root

  vars_files:
  - vars.yml

  vars:
    daemons: [ 'registry' ]

  tasks:

  - file: path=/etc/apt/sources.list.d/ state=directory mode=0755
  - template: src=./files/common/etc/apt/sources.list.d/docker.list  dest=/etc/apt/sources.list.d/docker.list
  - shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

  - apt: upgrade=yes update_cache=yes
  - apt: pkg=docker-engine state=present

  - template: src=files/master/lib/systemd/system/docker.service dest=/lib/systemd/system/docker.service
  - shell: systemctl daemon-reload
  - service: state=restarted name=docker

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - template: src=./files/master/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run mode=0700
    with_items:
      - "{{ daemons }}"
    notify: restart-services

  - template: src=./files/master/usr/service/{{ item }}/log/run dest=/usr/service/{{ item }}/log/run mode=0700
    with_items:
      - "{{ daemons }}"

  - file: path=/etc/service/ state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - "{{ daemons }}"
    notify: restart-services

  - apt: pkg={{ item }} state=present
    with_items:
      - daemontools-run

####### nginx
  - file: path=/root/registry/nginx state=directory mode=0755
  - template: src=files/registry/nginx/Dockerfile dest=/root/registry/nginx/Dockerfile
  - template: src=files/registry/nginx/nginx.conf dest=/root/registry/nginx/nginx.conf

  - shell: 'docker build -t test/nginx /root/registry/nginx \
&& docker tag test/nginx {{ ansible_default_ipv4.address }}:5000/test/nginx \
&& docker push {{ ansible_default_ipv4.address }}:5000/test/nginx '

####### nginx-lvs-tun
  - file: path=/root/registry/nginx-lvs-tun state=directory mode=0755
  - template: src=files/registry/nginx-lvs-tun/Dockerfile dest=/root/registry/nginx-lvs-tun/Dockerfile
  - template: src=files/registry/nginx-lvs-tun/nginx.conf dest=/root/registry/nginx-lvs-tun/nginx.conf
  - template: src=files/registry/nginx-lvs-tun/server.sh dest=/root/registry/nginx-lvs-tun/server.sh mode=0755

  - shell: 'docker build -t test/nginx-lvs-tun /root/registry/nginx-lvs-tun \
&& docker tag test/nginx-lvs-tun {{ ansible_default_ipv4.address }}:5000/test/nginx-lvs-tun \
&& docker push {{ ansible_default_ipv4.address }}:5000/test/nginx-lvs-tun '

####### vrrp
  - file: path=/root/registry/vrrp state=directory mode=0755
  - template: src=files/registry/vrrp/Dockerfile dest=/root/registry/vrrp/Dockerfile
  - template: src=files/registry/vrrp/vrrp.conf dest=/root/registry/vrrp/vrrp.conf
  - template: src=files/registry/vrrp/to_master.sh dest=/root/registry/vrrp/to_master.sh mode=0755

  - shell: 'docker build -t test/keepalived /root/registry/vrrp \
&& docker tag test/keepalived {{ ansible_default_ipv4.address }}:5000/test/keepalived \
&& docker push {{ ansible_default_ipv4.address }}:5000/test/keepalived '

  handlers:

  - name: restart-services
    shell: 'svc -t /etc/service/* ; sleep 3'

