#!/bin/sh -e

if [ "$IFACE" = "eth0" ] ; then

/sbin/iptables -t mangle  -C PREROUTING -p tcp -m multiport -s {{ host_iprange }} --dports 80,443 -j MARK --set-mark 443 || \
/sbin/iptables -t mangle  -A PREROUTING -p tcp -m multiport -s {{ host_iprange }} --dports 80,443 -j MARK --set-mark 443

/sbin/iptables -t mangle  -C PREROUTING -p tcp -m multiport -s {{ container_iprange }} --dports 80,443 -j MARK --set-mark 443 || \
/sbin/iptables -t mangle  -A PREROUTING -p tcp -m multiport -s {{ container_iprange }} --dports 80,443 -j MARK --set-mark 443

/sbin/iptables -t nat -C PREROUTING -p tcp -m multiport  -m mark ! --mark 443 --dports 80,443 -j DNAT --to {{ vip }} || \
/sbin/iptables -t nat -I PREROUTING -p tcp -m multiport  -m mark ! --mark 443 --dports 80,443 -j DNAT --to {{ vip }} 

fi

