#!/bin/bash

exec 2>&1

export https_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888
export http_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888
#export no_proxy={{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:5000

exec /usr/bin/dockerd \
	--insecure-registry {% for host in groups['registry'] %} {{ hostvars[host]['ansible_default_ipv4']['address'] }}:5000 {% endfor %}

#	--iptables=false \
#	--userland-proxy=false \
#	--bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} --ip-masq=${FLANNEL_IPMASQ} \
#	--storage-driver=overlay2 \
