#!/bin/bash

exec 2>&1

export https_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888
export http_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888

exec /usr/local/bin/containerd

