#!/bin/bash

exec 2>&1
exec /usr/local/bin/etcd  \
	--listen-client-urls http://0.0.0.0:2379 \
	--listen-peer-urls http://0.0.0.0:2380 \
        --advertise-client-urls http://{{ ansible_default_ipv4.address }}:2379 \
	--initial-cluster default=http://{{ ansible_default_ipv4.address }}:2380 \
        --initial-advertise-peer-urls http://{{ ansible_default_ipv4.address }}:2380 \
	--data-dir /var/lib/etcd/data 

