#!/bin/bash

exec 2>&1

export https_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888
export http_proxy=http://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:8888
#export no_proxy={{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:5000

exec /usr/bin/dockerd \
        --iptables=false \
        --ip-masq=false \
        --bridge="cbr0" \
	--fixed-cidr={{ ansible_default_ipv4.address }}/24
	--insecure-registry {% for host in groups['registry'] %} {{ hostvars[host]['ansible_default_ipv4']['address'] }}:5000 {% endfor %}

