#!/bin/bash

exec 2>&1
exec /usr/bin/dockerd \
        --iptables=false \
        --ip-masq=false \
        --bridge="cbr0" \
	--fixed-cidr={{ ansible_default_ipv4.address }}/24 \
	--insecure-registry {% for host in groups['registry'] %} {{ hostvars[host]['ansible_default_ipv4']['address'] }}:5000 {% endfor %}

