#!/bin/bash

exec 2>&1
exec /usr/local/bin/apiserver \
 	--insecure-bind-address=0.0.0.0 \
 	--bind-address=0.0.0.0 \
 	--secure-port=443 \
 	--etcd-servers=http://127.0.0.1:2379 \
	--service-cluster-ip-range=10.254.0.0/16 \
	--service-node-port-range=30000-32767 \
 	--logtostderr=true \
	--client-ca-file=/srv/kubernetes/ca.crt \
	--tls-cert-file=/srv/kubernetes/server.crt \
	--tls-private-key-file=/srv/kubernetes/server.key \
	--service-account-key-file=/srv/kubernetes/server.key \
	--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota \
	--cloud-provider="" \
	--v 2 \
	--allow-privileged=true \

