#!/bin/bash

exec 2>&1
exec /usr/local/bin/kubelet  \
        --api-servers={% for host in groups['masters'] %}https://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:443{% if not loop.last %},{% endif %}{% endfor %} \
	--cert-dir=/var/lib/kubelet/tls \
	--v 2

