#!/bin/bash

exec 2>&1
exec /usr/local/bin/kubelet  \
	--allow-privileged=true \
	--anonymous-auth=false \
	--authorization-mode=Webhook \
	--client-ca-file=/var/lib/kubernetes/ca.pem \
	--cluster-dns=10.32.0.10 \
	--cluster-domain=cluster.local \
	--container-runtime=remote \
	--container-runtime-endpoint=unix:///var/run/cri-containerd.sock \
	--image-pull-progress-deadline=2m \
	--kubeconfig=/var/lib/kubernetes/{{ inventory_hostname }}.kubeconfig \
	--network-plugin=cni \
	--pod-cidr={{ flannel_iprange }} \
	--register-node=true \
	--require-kubeconfig \
	--runtime-request-timeout=15m \
	--tls-cert-file=/var/lib/kubernetes/{{ inventory_hostname }}.pem \
	--tls-private-key-file=/var/lib/kubernetes/{{ inventory_hostname }}-key.pem \
	--v=2

